### ISSUE TITLE
Does not support iPhone X

### ISSUE THREAD

**Issue by simonemarinelli** [merryjs/photo-viewer#40] opened 2018-02-06 14:41 UTC

**Comment by bang88** [comment] 2018-02-07 07:57
Does it crashes or something else ?

**Comment by simonemarinelli** [comment] 2018-02-07 09:17
No crashes.
It's only a graphic problem.
I attach 2 images below.

![landscape](https://user-images.githubusercontent.com/14885349/35907985-bc1f7420-0bef-11e8-95c8-68ea589ac7c9.jpeg)
![portrait](https://user-images.githubusercontent.com/14885349/35907986-bc418b96-0bef-11e8-9fea-dabdb2ca74f7.jpeg)

**Comment by bang88** [comment] 2018-02-07 09:24
The issue is come from NYT PhotoViewer should fixed in upstream.

**Comment by CrazyPython** [comment] 2018-02-10 00:44
@bang88 It seems like NYTPhotoViewer has been updated and on cocoapods https://github.com/NYTimes/NYTPhotoViewer/pull/249

**Comment by bang88** [comment] 2018-02-21 14:29
@CrazyPython It seems problem are still there. not fixed

**Comment by CrazyPython** [comment] 2018-03-01 21:30
Can you check again? Maybe update NYTPhotoViewer to 2.0.0

**Comment by bang88** [comment] 2018-03-02 00:55
You can have a check I have upgrade to version 2.0.0 already

**Comment by simonemarinelli** [comment] 2018-04-23 09:48
Same problem

**Closed** 2018-04-28 04:33 UTC
Labels: watchlist
